"""actualizar url foto obra

Revision ID: 250e274abb68
Revises: 96656a47b80d
Create Date: 2025-06-28 17:21:11.628831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250e274abb68'
down_revision: Union[str, Sequence[str], None] = '96656a47b80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('imagen_obra', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obras', 'imagen_obra')
    # ### end Alembic commands ###
