"""actualizar tabla obras

Revision ID: 5d9ce39257a8
Revises: ebec40c271ce
Create Date: 2025-06-27 09:45:06.109636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9ce39257a8'
down_revision: Union[str, Sequence[str], None] = 'ebec40c271ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('nombre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obras', 'nombre')
    # ### end Alembic commands ###
