"""modificacion tabla solicitud

Revision ID: 5ea115e7b42e
Revises: 5d9ce39257a8
Create Date: 2025-06-27 19:46:50.017883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea115e7b42e'
down_revision: Union[str, Sequence[str], None] = '5d9ce39257a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
