"""agregar tabla perfil

Revision ID: 831a19fd6453
Revises: 
Create Date: 2025-06-21 16:52:01.642449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831a19fd6453'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items', checkfirst=True)
    op.drop_index(op.f('ix_items_name'), table_name='items', checkfirst=True)
    op.drop_table('items', checkfirst=True)
    op.add_column('usuarios', sa.Column('id_perfil', sa.Integer(), nullable=True), checkfirst=True)
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios', checkfirst=True)
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios', checkfirst=True)
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios', checkfirst=True)
    op.create_unique_constraint(None, 'usuarios', ['correo'], checkfirst=True)
    op.create_foreign_key(None, 'usuarios', 'perfiles', ['id_perfil'], ['id'], checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey', checkfirst=True)
    op.drop_constraint(None, 'usuarios', type_='unique', checkfirst=True)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False, checkfirst=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False, checkfirst=True)
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True, checkfirst=True)
    op.drop_column('usuarios', 'id_perfil', checkfirst=True)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    , checkfirst=True)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True, checkfirst=True)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False, checkfirst=True)
    # ### end Alembic commands ###
