"""actualizar url foot

Revision ID: 96656a47b80d
Revises: 5ea115e7b42e
Create Date: 2025-06-28 17:17:27.689124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96656a47b80d'
down_revision: Union[str, Sequence[str], None] = '5ea115e7b42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obras', sa.Column('imagen_obra', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obras', 'imagen_obra')
    # ### end Alembic commands ###
