"""nuevas tablas y relaciones

Revision ID: ebec40c271ce
Revises: f6f5b7168705
Create Date: 2025-06-21 21:11:03.694174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebec40c271ce'
down_revision: Union[str, Sequence[str], None] = 'f6f5b7168705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tecnica', sa.String(), nullable=True),
    sa.Column('nivel_apreciacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tecnica', sa.Integer(), nullable=True),
    sa.Column('id_artista', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('dimensiones', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['artistas.id'], ),
    sa.ForeignKeyConstraint(['id_tecnica'], ['tecnicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solictitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=True),
    sa.Column('id_obra', sa.Integer(), nullable=True),
    sa.Column('id_evaluador_artistico', sa.Integer(), nullable=True),
    sa.Column('aprobadaEvaluadorArtistico', sa.Boolean(), nullable=True),
    sa.Column('aprobadaEValuadorEconomico', sa.Boolean(), nullable=True),
    sa.Column('porcentaje_ganancia', sa.Integer(), nullable=True),
    sa.Column('precio_venta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['artistas.id'], ),
    sa.ForeignKeyConstraint(['id_evaluador_artistico'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_obra'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solictitudes')
    op.drop_table('obras')
    op.drop_table('tecnicas')
    op.drop_table('artistas')
    # ### end Alembic commands ###
